apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Pod
metadata:
  name: dev-nginx-pod
  namespace: dev
spec:
  containers:
  - name: dev-nginx-pod
    image: nginx:latest

---
# Create a pod named httpd-pod with a container named httpd-container. Use the httpd image with the latest tag (specify as httpd:latest). Set the following resource limits:

# Requests: Memory: 15Mi, CPU: 100m

# Limits: Memory: 20Mi, CPU: 100m

apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
spec:
  containers:
  - name: httpd-container
    image: httpd:latest
    resources:
      requests:
        memory: 15Mi
        cpu: 100m
      limits:
        memory: 20Mi
        cpu: 100m

---
apiVersion: v1
kind: ReplicaSet
metadata:
  name: httpd-replicaset
  labels:
    app: httpd_app
    type: front-end
spec:
  replicaSet: 4
  selector:
    matchLabels:
      app: httpd_app
      type: front-end
  template:
    metadata:
      name: httpd-replicaset
      labels:
        app: httpd_app
        type: front-end
    spec:
      containers:
        - name: httpd-container
          image: httpd:latest
